### ISSUE TITLE
ModuleNotFoundError: No module named 'general_funcs'

### ISSUE THREAD

**Issue by sousasag** [telmonteiro/PEEC-24#3]
After passin the pyrkh, I am getting another module error:
```

python SAITAMA_run.py 
Traceback (most recent call last):
  File "/home/sousasag/Programas/GIT_projects/Others/SAITAMA/SAITAMA_run.py", line 15, in <module>
    from SAITAMA import SAITAMA
  File "/home/sousasag/Programas/GIT_projects/Others/SAITAMA/SAITAMA.py", line 69, in <module>
    from pipeline_functions.RV_correction_funcs import (get_rv_ccf, correct_spec_rv, get_betaRV)
  File "/home/sousasag/Programas/GIT_projects/Others/SAITAMA/pipeline_functions/RV_correction_funcs.py", line 6, in <module>
    from general_funcs import (calc_fits_wv_1d, read_fits)
ModuleNotFoundError: No module named 'general_funcs'
```
I see the py file also inside pipeline_functions. Maybe you added this folder to the path? or you have it configured to use all subfolder, if that is possible... ???

**Comment by telmonteiro** [comment]
I think the problem is very similar to the other issue regarding pyrhk. I solved it in my machine a few months ago, but indeed when I downloaded the repository and tested the pyrhk problem appeared.

By solving that problem (https://github.com/telmonteiro/SAITAMA/issues/1#issuecomment-2324856537), no more bugs appeared, namely with the general_funcs.py file. I think adding the absolute path solves both of the problems.
